nodeLinker: node-modules
nmHoistingLimits: workspaces
checksumBehavior: ignore # ignore checksums for now, because they are failing in Windows (https://github.com/yarnpkg/berry/issues/5795). Remove this line once that's solved.
