checksumBehavior: ignore
nmHoistingLimits: workspaces
nodeLinker: node-modules
plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

packageExtensions:
    # deasync didn't add node-gyp as a direct dependency so it fails to build in
    # Yarn (https://github.com/yarnpkg/berry/issues/5804), so extend its
    # pkg.json config here.
    deasync@*:
        dependencies:
            node-gyp: 'latest'
