progressBarStyle: patrick # "patrick" | "simba" | "jack" | "hogsfather" | "default",

# without this, Windows was failing to pass checksum validation.
# checksumBehavior: ignore

# Tells Yarn to install packages to `node_modules`. Without this, it uses its
# more magical .pnp files, which change the Node runtime to find packages in a
# different way outside of node_modules, and this does not work for our
# client-side projects and import maps that we've set up to find packages in
# node_modules. It would be too cubersome to have the import maps map to .yarn/
# cache locations which include ugly hashes in their name.
nodeLinker: node-modules

# Hoist dependencies up to workspace boundaries, rather than all the way up to
# the root. Without this, importmaps in a client-side examples would not be able
# to access dependencies because node_modules would not exist in the local
# project.
nmHoistingLimits: workspaces

# Yarn recommends enabling this with Yarn 4.0.0 to catch version constraint
# errors locally before running in CI. In particular, when enabled, Yarn
# enforces that no two workspaces depend on different versions of any given
# dependencies, unless explicitly allowed.
# (https://yarnpkg.com/blog/release/4.0)
enableConstraintsChecks: true

# Define whether to reuse most common dependency ranges or not when adding dependencies to a package.
# If true, yarn add will attempt to reuse the most common dependency range in other workspaces.
preferReuse: true
