name: tests

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                # TODO get tests working in Windows and macOS (help wanted!)
                # windows-latest
                # macos-latest
                operating-system: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: 'recursive'
                  token: ${{ secrets.ACCESS_TOKEN }}
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: lts/-2 # the last two lts versions is good enough
            - name: npm install, build, and test
              run: |
                  npm run fresh
                  npm run test:all:ci
              env:
                  CI: true
